/**
 * Stock API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package me.notisfy.stock.domain.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;
import me.notisfy.stock.domain.model.ArticleFileItem;


/**
 * ArticleIndex
 */

public class ArticleIndex   {
  @SerializedName("version")
  private String version = null;

  @SerializedName("recent")
  private String recent = null;

  @SerializedName("last")
  private Integer last = null;

  @SerializedName("files")
  private List<ArticleFileItem> files = new ArrayList<ArticleFileItem>();

  public ArticleIndex version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Article index 버전
   * @return version
  **/
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public ArticleIndex recent(String recent) {
    this.recent = recent;
    return this;
  }

   /**
   * 마지막 전략 글
   * @return recent
  **/
  public String getRecent() {
    return recent;
  }

  public void setRecent(String recent) {
    this.recent = recent;
  }

  public ArticleIndex last(Integer last) {
    this.last = last;
    return this;
  }

   /**
   * 마지막 인덱스 번호
   * @return last
  **/
  public Integer getLast() {
    return last;
  }

  public void setLast(Integer last) {
    this.last = last;
  }

  public ArticleIndex files(List<ArticleFileItem> files) {
    this.files = files;
    return this;
  }

  public ArticleIndex addFilesItem(ArticleFileItem filesItem) {
    this.files.add(filesItem);
    return this;
  }

   /**
   * Article 파일 정보
   * @return files
  **/
  public List<ArticleFileItem> getFiles() {
    return files;
  }

  public void setFiles(List<ArticleFileItem> files) {
    this.files = files;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArticleIndex articleIndex = (ArticleIndex) o;
    return Objects.equals(this.version, articleIndex.version) &&
        Objects.equals(this.recent, articleIndex.recent) &&
        Objects.equals(this.last, articleIndex.last) &&
        Objects.equals(this.files, articleIndex.files);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, recent, last, files);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArticleIndex {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    recent: ").append(toIndentedString(recent)).append("\n");
    sb.append("    last: ").append(toIndentedString(last)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

