/**
 * Stock API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package me.notisfy.stock.domain.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;
import me.notisfy.stock.domain.model.BotHoldingsDiffItem;
import me.notisfy.stock.domain.model.BotHoldingsItem;
import me.notisfy.stock.domain.model.VolumeFeaturedItem;


/**
 * TodaySummary
 */

public class TodaySummary   {
  @SerializedName("version")
  private String version = null;

  @SerializedName("kospi_today")
  private String kospiToday = null;

  @SerializedName("kospi_diff")
  private String kospiDiff = null;

  @SerializedName("featured_today")
  private List<VolumeFeaturedItem> featuredToday = new ArrayList<VolumeFeaturedItem>();

  @SerializedName("holdings_today")
  private List<BotHoldingsItem> holdingsToday = new ArrayList<BotHoldingsItem>();

  @SerializedName("holdings_diff")
  private List<BotHoldingsDiffItem> holdingsDiff = new ArrayList<BotHoldingsDiffItem>();

  public TodaySummary version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Today summary 버전
   * @return version
  **/
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public TodaySummary kospiToday(String kospiToday) {
    this.kospiToday = kospiToday;
    return this;
  }

   /**
   * 오늘의 코스피 지수
   * @return kospiToday
  **/
  public String getKospiToday() {
    return kospiToday;
  }

  public void setKospiToday(String kospiToday) {
    this.kospiToday = kospiToday;
  }

  public TodaySummary kospiDiff(String kospiDiff) {
    this.kospiDiff = kospiDiff;
    return this;
  }

   /**
   * 코스피 변동량
   * @return kospiDiff
  **/
  public String getKospiDiff() {
    return kospiDiff;
  }

  public void setKospiDiff(String kospiDiff) {
    this.kospiDiff = kospiDiff;
  }

  public TodaySummary featuredToday(List<VolumeFeaturedItem> featuredToday) {
    this.featuredToday = featuredToday;
    return this;
  }

  public TodaySummary addFeaturedTodayItem(VolumeFeaturedItem featuredTodayItem) {
    this.featuredToday.add(featuredTodayItem);
    return this;
  }

   /**
   * 오늘의 거래량 특징주
   * @return featuredToday
  **/
  public List<VolumeFeaturedItem> getFeaturedToday() {
    return featuredToday;
  }

  public void setFeaturedToday(List<VolumeFeaturedItem> featuredToday) {
    this.featuredToday = featuredToday;
  }

  public TodaySummary holdingsToday(List<BotHoldingsItem> holdingsToday) {
    this.holdingsToday = holdingsToday;
    return this;
  }

  public TodaySummary addHoldingsTodayItem(BotHoldingsItem holdingsTodayItem) {
    this.holdingsToday.add(holdingsTodayItem);
    return this;
  }

   /**
   * 오늘의 보유 주식
   * @return holdingsToday
  **/
  public List<BotHoldingsItem> getHoldingsToday() {
    return holdingsToday;
  }

  public void setHoldingsToday(List<BotHoldingsItem> holdingsToday) {
    this.holdingsToday = holdingsToday;
  }

  public TodaySummary holdingsDiff(List<BotHoldingsDiffItem> holdingsDiff) {
    this.holdingsDiff = holdingsDiff;
    return this;
  }

  public TodaySummary addHoldingsDiffItem(BotHoldingsDiffItem holdingsDiffItem) {
    this.holdingsDiff.add(holdingsDiffItem);
    return this;
  }

   /**
   * 보유 주식 변동량
   * @return holdingsDiff
  **/
  public List<BotHoldingsDiffItem> getHoldingsDiff() {
    return holdingsDiff;
  }

  public void setHoldingsDiff(List<BotHoldingsDiffItem> holdingsDiff) {
    this.holdingsDiff = holdingsDiff;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TodaySummary todaySummary = (TodaySummary) o;
    return Objects.equals(this.version, todaySummary.version) &&
        Objects.equals(this.kospiToday, todaySummary.kospiToday) &&
        Objects.equals(this.kospiDiff, todaySummary.kospiDiff) &&
        Objects.equals(this.featuredToday, todaySummary.featuredToday) &&
        Objects.equals(this.holdingsToday, todaySummary.holdingsToday) &&
        Objects.equals(this.holdingsDiff, todaySummary.holdingsDiff);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, kospiToday, kospiDiff, featuredToday, holdingsToday, holdingsDiff);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TodaySummary {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    kospiToday: ").append(toIndentedString(kospiToday)).append("\n");
    sb.append("    kospiDiff: ").append(toIndentedString(kospiDiff)).append("\n");
    sb.append("    featuredToday: ").append(toIndentedString(featuredToday)).append("\n");
    sb.append("    holdingsToday: ").append(toIndentedString(holdingsToday)).append("\n");
    sb.append("    holdingsDiff: ").append(toIndentedString(holdingsDiff)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

