/**
 * Stock API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package me.notisfy.stock.domain.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


/**
 * VolumeFeaturedProfitItem
 */

public class VolumeFeaturedProfitItem   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("profit")
  private String profit = null;

  @SerializedName("featuredDate")
  private String featuredDate = null;

  @SerializedName("featuredVolumeInc")
  private String featuredVolumeInc = null;

  public VolumeFeaturedProfitItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 종목명
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VolumeFeaturedProfitItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 종목코드
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VolumeFeaturedProfitItem profit(String profit) {
    this.profit = profit;
    return this;
  }

   /**
   * 거래량 특징이 나타난후 최고/최저가 비율
   * @return profit
  **/
  public String getProfit() {
    return profit;
  }

  public void setProfit(String profit) {
    this.profit = profit;
  }

  public VolumeFeaturedProfitItem featuredDate(String featuredDate) {
    this.featuredDate = featuredDate;
    return this;
  }

   /**
   * 최고 이익률이 가능한 거래량 특징일이 나타난 날짜 (최대 2주전)
   * @return featuredDate
  **/
  public String getFeaturedDate() {
    return featuredDate;
  }

  public void setFeaturedDate(String featuredDate) {
    this.featuredDate = featuredDate;
  }

  public VolumeFeaturedProfitItem featuredVolumeInc(String featuredVolumeInc) {
    this.featuredVolumeInc = featuredVolumeInc;
    return this;
  }

   /**
   * 거래량 특징이 나타난 날짜의 거래량 증가 비율
   * @return featuredVolumeInc
  **/
  public String getFeaturedVolumeInc() {
    return featuredVolumeInc;
  }

  public void setFeaturedVolumeInc(String featuredVolumeInc) {
    this.featuredVolumeInc = featuredVolumeInc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VolumeFeaturedProfitItem volumeFeaturedProfitItem = (VolumeFeaturedProfitItem) o;
    return Objects.equals(this.name, volumeFeaturedProfitItem.name) &&
        Objects.equals(this.id, volumeFeaturedProfitItem.id) &&
        Objects.equals(this.profit, volumeFeaturedProfitItem.profit) &&
        Objects.equals(this.featuredDate, volumeFeaturedProfitItem.featuredDate) &&
        Objects.equals(this.featuredVolumeInc, volumeFeaturedProfitItem.featuredVolumeInc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, profit, featuredDate, featuredVolumeInc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VolumeFeaturedProfitItem {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    profit: ").append(toIndentedString(profit)).append("\n");
    sb.append("    featuredDate: ").append(toIndentedString(featuredDate)).append("\n");
    sb.append("    featuredVolumeInc: ").append(toIndentedString(featuredVolumeInc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

