/**
 * Stock API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package me.notisfy.stock.domain.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;
import me.notisfy.stock.domain.model.VolumeFeaturedDaysItem;


/**
 * VolumeFeaturedDays
 */

public class VolumeFeaturedDays   {
  @SerializedName("version")
  private String version = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("dailyTrading")
  private List<VolumeFeaturedDaysItem> dailyTrading = new ArrayList<VolumeFeaturedDaysItem>();

  public VolumeFeaturedDays version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Volume featured days 버전
   * @return version
  **/
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public VolumeFeaturedDays name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 주식 이름
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VolumeFeaturedDays dailyTrading(List<VolumeFeaturedDaysItem> dailyTrading) {
    this.dailyTrading = dailyTrading;
    return this;
  }

  public VolumeFeaturedDays addDailyTradingItem(VolumeFeaturedDaysItem dailyTradingItem) {
    this.dailyTrading.add(dailyTradingItem);
    return this;
  }

   /**
   * 거래량 특징일 리스트
   * @return dailyTrading
  **/
  public List<VolumeFeaturedDaysItem> getDailyTrading() {
    return dailyTrading;
  }

  public void setDailyTrading(List<VolumeFeaturedDaysItem> dailyTrading) {
    this.dailyTrading = dailyTrading;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VolumeFeaturedDays volumeFeaturedDays = (VolumeFeaturedDays) o;
    return Objects.equals(this.version, volumeFeaturedDays.version) &&
        Objects.equals(this.name, volumeFeaturedDays.name) &&
        Objects.equals(this.dailyTrading, volumeFeaturedDays.dailyTrading);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, name, dailyTrading);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VolumeFeaturedDays {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    dailyTrading: ").append(toIndentedString(dailyTrading)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

