/**
 * Stock API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package me.notisfy.stock.domain.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;


/**
 * VolumeFeaturedItem
 */

public class VolumeFeaturedItem   {
  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("volumeInc")
  private String volumeInc = null;

  @SerializedName("price")
  private String price = null;

  @SerializedName("priceInc")
  private String priceInc = null;

  public VolumeFeaturedItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * 종목명
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public VolumeFeaturedItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * 종목코드
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public VolumeFeaturedItem volumeInc(String volumeInc) {
    this.volumeInc = volumeInc;
    return this;
  }

   /**
   * 거래 증가 비율
   * @return volumeInc
  **/
  public String getVolumeInc() {
    return volumeInc;
  }

  public void setVolumeInc(String volumeInc) {
    this.volumeInc = volumeInc;
  }

  public VolumeFeaturedItem price(String price) {
    this.price = price;
    return this;
  }

   /**
   * 수정 종가
   * @return price
  **/
  public String getPrice() {
    return price;
  }

  public void setPrice(String price) {
    this.price = price;
  }

  public VolumeFeaturedItem priceInc(String priceInc) {
    this.priceInc = priceInc;
    return this;
  }

   /**
   * 전일 수정 종가 대비 가격 상승 비율
   * @return priceInc
  **/
  public String getPriceInc() {
    return priceInc;
  }

  public void setPriceInc(String priceInc) {
    this.priceInc = priceInc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VolumeFeaturedItem volumeFeaturedItem = (VolumeFeaturedItem) o;
    return Objects.equals(this.name, volumeFeaturedItem.name) &&
        Objects.equals(this.id, volumeFeaturedItem.id) &&
        Objects.equals(this.volumeInc, volumeFeaturedItem.volumeInc) &&
        Objects.equals(this.price, volumeFeaturedItem.price) &&
        Objects.equals(this.priceInc, volumeFeaturedItem.priceInc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, volumeInc, price, priceInc);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VolumeFeaturedItem {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    volumeInc: ").append(toIndentedString(volumeInc)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    priceInc: ").append(toIndentedString(priceInc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

